NATIONALITY_TO_FLAG_EMOJI: dict[str, str] = {
    "Slovenia": "🇸🇮", "Denmark": "🇩🇰", "Belgium": "🇧🇪", "Netherlands": "🇳🇱",
    "France": "🇫🇷", "Spain": "🇪🇸", "Colombia": "🇨🇴", "Italy": "🇮🇹",
    "Australia": "🇦🇺", "Great Britain": "🇬🇧", "United Kingdom": "🇬🇧",
    "Norway": "🇳🇴", "Germany": "🇩🇪", "Portugal": "🇵🇹", "Eritrea": "🇪🇷",
    "Ecuador": "🇪🇨", "United States": "🇺🇸", "Switzerland": "🇨🇭",
    "Ireland": "🇮🇪", "Poland": "🇵🇱", "Kazakhstan": "🇰🇿",
    "Palestine": "🇵🇸",
}

FLAG_CODE_TO_COUNTRY: dict[str, str] = {
    "af": "Afghanistan", "al": "Albania", "dz": "Algeria", "ad": "Andorra",
    "ao": "Angola", "ar": "Argentina", "am": "Armenia", "au": "Australia",
    "at": "Austria", "az": "Azerbaijan", "bh": "Bahrain", "by": "Belarus",
    "be": "Belgium", "bj": "Benin", "bo": "Bolivia", "ba": "Bosnia",
    "bw": "Botswana", "br": "Brazil", "bg": "Bulgaria", "bf": "Burkina Faso",
    "cm": "Cameroon", "ca": "Canada", "cv": "Cape Verde", "cl": "Chile",
    "cn": "China", "co": "Colombia", "cr": "Costa Rica", "hr": "Croatia",
    "cu": "Cuba", "cz": "Czech Republic", "dk": "Denmark", "do": "Dominican Republic",
    "ec": "Ecuador", "eg": "Egypt", "sv": "El Salvador", "er": "Eritrea",
    "ee": "Estonia", "et": "Ethiopia", "fi": "Finland", "fr": "France",
    "ga": "Gabon", "ge": "Georgia", "de": "Germany", "gh": "Ghana",
    "gr": "Greece", "gt": "Guatemala", "gn": "Guinea", "hn": "Honduras",
    "hk": "Hong Kong", "hu": "Hungary", "is": "Iceland", "in": "India",
    "id": "Indonesia", "ir": "Iran", "iq": "Iraq", "ie": "Ireland",
    "il": "Israel", "it": "Italy", "jm": "Jamaica", "jp": "Japan",
    "jo": "Jordan", "kz": "Kazakhstan", "ke": "Kenya", "xk": "Kosovo",
    "kw": "Kuwait", "kg": "Kyrgyzstan", "lv": "Latvia", "lb": "Lebanon",
    "ly": "Libya", "li": "Liechtenstein", "lt": "Lithuania", "lu": "Luxembourg",
    "mk": "North Macedonia", "mg": "Madagascar", "mw": "Malawi", "my": "Malaysia",
    "mv": "Maldives", "ml": "Mali", "mt": "Malta", "mr": "Mauritania",
    "mx": "Mexico", "md": "Moldova", "mc": "Monaco", "mn": "Mongolia",
    "me": "Montenegro", "ma": "Morocco", "mz": "Mozambique", "na": "Namibia",
    "nl": "Netherlands", "nz": "New Zealand", "ni": "Nicaragua", "ng": "Nigeria",
    "no": "Norway", "om": "Oman", "pk": "Pakistan", "pa": "Panama", "ps": "Palestine",
    "py": "Paraguay", "pe": "Peru", "ph": "Philippines", "pl": "Poland",
    "pt": "Portugal", "qa": "Qatar", "ro": "Romania", "ru": "Russia",
    "rw": "Rwanda", "sa": "Saudi Arabia", "sn": "Senegal", "rs": "Serbia",
    "si": "Slovenia", "so": "Somalia", "za": "South Africa", "es": "Spain",
    "lk": "Sri Lanka", "sd": "Sudan", "se": "Sweden", "ch": "Switzerland",
    "sy": "Syria", "tw": "Taiwan", "tj": "Tajikistan", "tz": "Tanzania",
    "th": "Thailand", "tg": "Togo", "tn": "Tunisia", "tr": "Turkey",
    "tm": "Turkmenistan", "ug": "Uganda", "ua": "Ukraine", "ae": "UAE",
    "gb": "Great Britain", "us": "USA", "uy": "Uruguay", "uz": "Uzbekistan",
    "ve": "Venezuela", "vn": "Vietnam", "ye": "Yemen", "zm": "Zambia",
    "zw": "Zimbabwe",
}


def flag_emoji(nationality: str | None) -> str:
    return NATIONALITY_TO_FLAG_EMOJI.get(nationality or "", "")
